### ISSUE TITLE
Fix JT-Line logo rendering 

### ISSUE THREAD

**Issue by huksley** [City-of-Helsinki/vesiliikenne-maas#47]
@karki 

```html
<img width={'30%'} src="/images/jt-logo.jpg" alt="JT-logo" />
```

WhimApp cannot follow relative links, either provide absolute url https://... or use embedded `<img src="data:image/jpeg;base64,...`

Would be also great to use SVG instead of JPG if possible.

**Comment by karki** [comment]
This is now fixed. We ended up going with a base64 encoded SVG representation. The logo data is given in the variable `logoData` as opposed to the previous `logoId`.
